spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Abik
          jwk-set-uri: http://localhost:8080/realms/Abik/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: abik-rest-api
      principle-attribute: preferred_username
